import { Manifest } from "../shared/types";
import { Events, makeEvents } from "./events";
import url from 'virtual:gallery:url';

/** Events emitted by manifest.events */
type ManifestEvents = {
    onLoaded: Manifest;
    onError: Error | string;
}
/** Manifest module. Streams in the manifest generated by the vite module. */
const manifest: Manifest & {
    /** Event Emitter. */
    events: Events<ManifestEvents>;
    /** Kicks off streamin in of the manifest data. */
    initAsync(): Promise<void>;
} = {
    tags: [],
    photos: {},
    events: makeEvents(),
    async initAsync() {
        try {
            const res = await fetch(url);
            const json = await res.json() as Partial<Manifest>;
            manifest.tags = json.tags ?? [];
            manifest.photos = json.photos ?? {};
            manifest.events.emit('onLoaded', manifest);
        } catch (e) {
            const err = ((e instanceof Error) || typeof e === 'string') ? e : 'Unknown Error';
            manifest.events.emit('onError', err);
        }
    }
}
export default manifest;
