import Binary from "../shared/binary";
import { Manifest, TagLoca } from "../shared/types";
import { Events, makeEvents } from "./events";
import generated from 'virtual:gallery:manifest';

/** Events emitted by manifest.events */
type ManifestEvents = {
    onLoaded: Manifest;
    onError: Error | string;
}
/** Manifest module. Streams in the manifest generated by the vite module. */
const manifest: Manifest & {
    /** Event Emitter. */
    events: Events<ManifestEvents>;
    /** Kicks off streamin in of the manifest data. */
    initAsync(): Promise<void>;
    /** Language => URL mapping for tag loca. */
    tagLoca: TagLoca;
} = {
    ...(new Binary(generated.data.buffer).readManifest()),
    tagLoca: generated.tagLoca,
    events: makeEvents(),
    async initAsync() {
        try {
            Object.entries(manifest.photos).forEach(([name, info]) => {
                info.image.url = generated.schema.image
                    .replace('#NAME#', name)
                    .replace('#HASH#', info.image.hash ?? '');
                info.thumb.url = generated.schema.thumb
                    .replace('#NAME#', name)
                    .replace('#HASH#', info.thumb.hash ?? '');
            });
            manifest.events.emit('onLoaded', manifest);
        } catch (e) {
            const err = ((e instanceof Error) || typeof e === 'string') ? e : 'Unknown Error';
            manifest.events.emit('onError', err);
        }
    }
}
export default manifest;
